publishDir = "docs"
canonifyURLs = true
baseurl = "https://jbrandhorst.com"
defaultContentLanguage = "en"
title = "Go Ahead"
theme = "hermit"
metaDataFormat = "yaml"
pygmentsCodefences  = true
pygmentsUseClasses  = true
googleAnalytics = "UA-96154465-1"

[params]
	homeSubtitle = "Go, gRPC and friends"
	dateform        = "Jan 2, 2006"
	dateformShort   = "Jan 2"
	dateformNum     = "2006-01-02"
	dateformNumTime = "2006-01-02 15:04 -0700"
	commit = false
	rss = true
	footerCopyright = ' &#183; Thanks to Netlify for hosting my blog'
	customCSS = ["css/main.css"]

	[[params.social]]
		name = "twitter"
		url = "https://twitter.com/JohanBrandhorst"

	[[params.social]]
		name = "github"
		url = "https://github.com/johanbrandhorst"

	[[params.social]]
		name = "linkedin"
		url = "https://www.linkedin.com/in/jbrandhorst/"

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
	  		unsafe = true

[Author]
	name = "Johan Brandhorst"

[[menu.main]]
	name = "Blog"
	url = "post/"
	weight = 1

[[menu.main]]
	name = "About"
	url = "page/about/"
	weight = 2

[[menu.main]]
	name = "Presentations"
	url = "page/presentations/"
	weight = 3
