publishDir = "docs"
canonifyURLs = true
baseurl = "https://jbrandhorst.com"
defaultContentLanguage = "en"
title = "Go Ahead"
theme = "hermit-v2"
metaDataFormat = "yaml"
pygmentsCodefences  = true
pygmentsUseClasses  = true

[params]
	homeSubtitle = "Go, gRPC and friends"
	dateform        = "Jan 2, 2006"
	dateformShort   = "Jan 2"
	dateformNum     = "2006-01-02"
	dateformNumTime = "2006-01-02 15:04 -0700"
	commit = false
	rss = true
	footerCopyright = 'Thanks to Netlify for hosting my blog '
	footerHideThemeName = true
	customCSS = ["css/main.css"]

	[[author]]
		name = "Johan Brandhorst-Satzkorn"

	[[params.social]]
		name = "bluesky"
		url = "https://bsky.app/profile/jbrandhorst.com"

	[[params.social]]
		name = "github"
		url = "https://github.com/johanbrandhorst"

	[[params.social]]
		name = "linkedin"
		url = "https://www.linkedin.com/in/jbrandhorst/"

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
	  		unsafe = true


[[menu.main]]
	name = "Blog"
	url = "post/"
	weight = 1

[[menu.main]]
	name = "About"
	url = "page/about/"
	weight = 2

[[menu.main]]
	name = "Presentations"
	url = "page/presentations/"
	weight = 3
